#!/usr/bin/env bun
/**
 * Use raffy's skills from Codex, Cursor and Gemini CLI.
 *
 *   bun scripts/agents.ts install [--dir <path>] [--dry]   write raffy-<skill>/ into ~/.agents/skills
 *   bun scripts/agents.ts uninstall [--dir <path>]          remove only what install wrote
 *   bun scripts/agents.ts snippet                           AGENTS.md lines that point an agent at the guide
 *
 * ~/.agents/skills is the user-level skill folder Codex, Cursor and Gemini CLI
 * all read (Gemini as an alias that wins over ~/.gemini/skills). Claude Code
 * reads ~/.claude/skills instead, so these copies never duplicate the plugin.
 *
 * Each SKILL.md is copied with ${CLAUDE_PLUGIN_ROOT} replaced by this repo's
 * absolute path — other agents do not set that variable — and its references/
 * and knowledge/ folders are symlinked so relative links still resolve. The
 * scripts run from the repo itself. Re-run install after moving the repo.
 *
 * What does not carry over: hooks. The guard, the proof check, the prompt hint
 * and the session brief are Claude Code hooks; other agents get the skills and
 * scripts only.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir } from "node:os";

const ROOT = resolve(import.meta.dir, "..");
const argv = process.argv.slice(2);
const cmd = argv[0];
const DIR = resolve(argv[argv.indexOf("--dir") + 1] && argv.includes("--dir") ? argv[argv.indexOf("--dir") + 1] : join(homedir(), ".agents", "skills"));
const DRY = argv.includes("--dry");
export const MARKER = ".raffy-generated";

const skills = () => readdirSync(join(ROOT, "skills")).filter((d) => existsSync(join(ROOT, "skills", d, "SKILL.md")));

function install() {
  mkdirSync(DIR, { recursive: true });
  const done: string[] = [];
  for (const name of skills()) {
    const src = join(ROOT, "skills", name);
    const dest = join(DIR, `raffy-${name}`);
    // Never overwrite a folder this script did not write.
    if (existsSync(dest) && !existsSync(join(dest, MARKER))) { console.error(`  skip  ${dest} exists and was not written by raffy`); continue; }
    let md = readFileSync(join(src, "SKILL.md"), "utf8").replaceAll("${CLAUDE_PLUGIN_ROOT}", ROOT);
    // Slash-command names differ outside Claude Code: /raffy:guide → the raffy-guide skill.
    md = md.replace(/^name:\s*\S+/m, `name: raffy-${name}`).replace(/\/raffy:([a-z-]+)/g, "the raffy-$1 skill");
    if (DRY) { done.push(dest); continue; }
    rmSync(dest, { recursive: true, force: true });
    mkdirSync(dest, { recursive: true });
    writeFileSync(join(dest, "SKILL.md"), md);
    writeFileSync(join(dest, MARKER), `generated by ${join(ROOT, "scripts", "agents.ts")} — rerun install to refresh\n`);
    for (const sub of ["references", "knowledge"]) if (existsSync(join(src, sub))) symlinkSync(join(src, sub), join(dest, sub));
    done.push(dest);
  }
  console.log(`${DRY ? "would install" : "installed"} ${done.length} skills into ${DIR.replace(homedir(), "~")} — Codex, Cursor and Gemini CLI read this folder`);
  console.log("hooks (guard, proof check, prompt hint, session brief) are Claude Code only and do not carry over");
}

function uninstall() {
  if (!existsSync(DIR)) return console.log("nothing installed");
  let n = 0;
  for (const d of readdirSync(DIR)) {
    const p = join(DIR, d);
    if (d.startsWith("raffy-") && statSync(p).isDirectory() && existsSync(join(p, MARKER))) { rmSync(p, { recursive: true, force: true }); n++; }
  }
  console.log(`removed ${n} raffy skills from ${DIR.replace(homedir(), "~")}`);
}

const snippet = `## raffy

Before choosing how to approach a task, read the raffy-guide skill. It works out where this project
is, picks the skill that fits, and explains why. Run its scripts exactly as written — one command
per call, full paths.`;

switch (cmd) {
  case "install": install(); break;
  case "uninstall": uninstall(); break;
  case "snippet": console.log(snippet); break;
  default:
    console.error("usage: agents.ts install [--dir <path>] [--dry] | uninstall [--dir <path>] | snippet");
    process.exit(2);
}
