#!/usr/bin/env bun
/**
 * Bundle other people's skills into library/, license-checked.
 *
 *   bun scripts/vendor.ts [--tiers core,often] [--dry]
 *
 * Bundled skills live in library/, NOT skills/. Claude Code only lists what is
 * under skills/, so a bundled skill costs zero context until the guide reads it
 * on purpose. That is the point: 60 bundled skills, 0 extra description tokens
 * per session.
 *
 * Refuses, and says why:
 *   - a skill with no entry in library/sources.json (origin unknown)
 *   - a source repo whose license is not in sources.json `allow`
 *   - a skill not found on this machine
 *
 * Writes library/<dir>/ (a copy), library/<dir>/SOURCE.json (provenance),
 * library/licenses/<owner>__<repo>.txt (the license text, fetched with gh),
 * and library/INDEX.tsv (what the catalog reads).
 */
import { cpSync, existsSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir } from "node:os";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { load } from "../skills/guide/scripts/catalog.ts";
import { scan } from "../skills/guide/scripts/inventory.ts";

const ROOT = resolve(import.meta.dir, "..");
const LIB = join(ROOT, "library");
const argv = process.argv.slice(2);
const DRY = argv.includes("--dry");
const tiers = (argv[argv.indexOf("--tiers") + 1] && argv.includes("--tiers") ? argv[argv.indexOf("--tiers") + 1] : "core,often").split(",");

const cfg = JSON.parse(readFileSync(join(LIB, "sources.json"), "utf8"));
const allow = new Set<string>(cfg.allow);
const installed = new Map(scan(ROOT).skills.map((s) => [s.id, s.path]));
export const dirFor = (id: string) => id.replace(/:/g, "--");

function locate(id: string): string | undefined {
  const bare = id.split(":").pop()!;
  const p = installed.get(id) ?? [join(homedir(), ".agents", "skills", bare), join(homedir(), ".claude", "skills", bare)].find((d) => existsSync(join(d, "SKILL.md")));
  return p ? realpathSync(p) : undefined;
}

function hashDir(dir: string): string {
  const h = createHash("sha256");
  (function walk(d: string) {
    for (const n of readdirSync(d).sort()) {
      const f = join(d, n);
      if (statSync(f).isDirectory()) walk(f); else h.update(n).update(readFileSync(f));
    }
  })(dir);
  return h.digest("hex").slice(0, 12);
}

function licenseText(repo: string): string | undefined {
  const r = spawnSync("gh", ["api", `repos/${repo}/license`, "--jq", ".content"], { encoding: "utf8" });
  if (r.status !== 0 || !r.stdout.trim()) return undefined;
  return Buffer.from(r.stdout.trim(), "base64").toString("utf8");
}

const rows = load().filter((r) => tiers.includes(r.tier) && !["raffy", "builtin", "command"].includes(r.src) && !r.src.startsWith("project:"));
const done: string[][] = [], refused: string[][] = [];
const licenses = new Map<string, string>();

for (const r of rows) {
  if ((cfg.own ?? []).includes(r.id)) { refused.push([r.id, "your own skill — kept out of the library by choice"]); continue; }
  const repo: string | undefined = cfg.skills[r.id];
  if (!repo) { refused.push([r.id, "origin unknown — add it to library/sources.json"]); continue; }
  const lic = cfg.repos[repo];
  if (!allow.has(lic)) { refused.push([r.id, `${repo} is ${lic === "NONE" ? "unlicensed" : lic} — cannot redistribute`]); continue; }
  const from = locate(r.id);
  if (!from) { refused.push([r.id, "not on this machine"]); continue; }

  const dir = dirFor(r.id);
  if (!DRY) {
    const to = join(LIB, dir);
    rmSync(to, { recursive: true, force: true });
    cpSync(from, to, { recursive: true, dereference: true, filter: (s) => !/\/(\.git|node_modules|__pycache__|\.DS_Store)(\/|$)/.test(s) });
    writeFileSync(join(to, "SOURCE.json"), JSON.stringify({ id: r.id, repo, license: lic, copiedFrom: from.replace(homedir(), "~"), hash: hashDir(to), vendoredAt: new Date().toISOString().slice(0, 10) }, null, 2) + "\n");
    if (!licenses.has(repo)) licenses.set(repo, licenseText(repo) ?? "");
  }
  done.push([r.id, dir, repo, lic]);
}

if (!DRY) {
  mkdirSync(join(LIB, "licenses"), { recursive: true });
  for (const [repo, text] of licenses) {
    if (!text) { console.error(`  warn  could not fetch license text for ${repo} — fetch it before publishing`); continue; }
    writeFileSync(join(LIB, "licenses", repo.replace("/", "__") + ".txt"), text);
  }
  writeFileSync(join(LIB, "INDEX.tsv"), "# id\tdir\trepo\tlicense — generated by scripts/vendor.ts, do not edit\n" + done.map((d) => d.join("\t")).join("\n") + "\n");
}

console.log(`${DRY ? "would bundle" : "bundled"} ${done.length} · refused ${refused.length}`);
for (const [id, why] of refused) console.log(`  skip  ${id} — ${why}`);
